export type InvoiceLanguage = "ja" | "en";

export const invoiceLabels = {
  ja: {
    documentTitle: "INVOICE",
    addresseeSuffix: " 御中",
    invoiceNumber: "請求番号",
    issueDate: "発行日",
    dueDate: "支払期限",
    registrationNumber: "登録番号",
    subject: "件名",
    amountDue: "ご請求金額",
    description: "品目",
    unitPrice: "単価",
    quantity: "数量",
    taxRate: "税率",
    lineSubtotal: "小計",
    lineTax: "税額",
    lineTotal: "合計",
    subtotal: "小計",
    tax: "消費税",
    total: "合計",
    bankInfo: "振込先",
    notes: "備考",
    draft: "下書き",
  },
  en: {
    documentTitle: "INVOICE",
    addresseeSuffix: "",
    invoiceNumber: "Invoice No.",
    issueDate: "Issue Date",
    dueDate: "Due Date",
    registrationNumber: "Registration No.",
    subject: "Subject",
    amountDue: "Amount Due",
    description: "Description",
    unitPrice: "Unit Price",
    quantity: "Qty",
    taxRate: "Tax Rate",
    lineSubtotal: "Subtotal",
    lineTax: "Tax",
    lineTotal: "Total",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    bankInfo: "Bank Details",
    notes: "Notes",
    draft: "DRAFT",
  },
} as const;

export type InvoiceLabelSet = (typeof invoiceLabels)[InvoiceLanguage];
